pkgname   = "model"
output    = "base/data/model"

[mysql]
  dbname    = "ellecube"
  host      = "127.0.0.1"
  port      = 3306
  user      = "root"
  pass      = ""
  sslmode   = "false"
  blacklist = ["schema_history", "schema_migrations"]
  whitelist = [
    "dtb_product",
    "dtb_product_category",
    "dtb_product_class",
    "dtb_product_image",
    "dtb_product_stock",
    "dtb_product_tag",
  ]
