// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// MTBSex is an object representing the database table.
type MTBSex struct {
	ID                uint16 `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name              string `boil:"name" json:"name" toml:"name" yaml:"name"`
	SortNo            uint16 `boil:"sort_no" json:"sort_no" toml:"sort_no" yaml:"sort_no"`
	DiscriminatorType string `boil:"discriminator_type" json:"discriminator_type" toml:"discriminator_type" yaml:"discriminator_type"`

	R *mtbSexR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L mtbSexL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MTBSexColumns = struct {
	ID                string
	Name              string
	SortNo            string
	DiscriminatorType string
}{
	ID:                "id",
	Name:              "name",
	SortNo:            "sort_no",
	DiscriminatorType: "discriminator_type",
}

// Generated where

var MTBSexWhere = struct {
	ID                whereHelperuint16
	Name              whereHelperstring
	SortNo            whereHelperuint16
	DiscriminatorType whereHelperstring
}{
	ID:                whereHelperuint16{field: `id`},
	Name:              whereHelperstring{field: `name`},
	SortNo:            whereHelperuint16{field: `sort_no`},
	DiscriminatorType: whereHelperstring{field: `discriminator_type`},
}

// MTBSexRels is where relationship names are stored.
var MTBSexRels = struct {
	SexDTBCustomers string
	SexDTBOrders    string
}{
	SexDTBCustomers: "SexDTBCustomers",
	SexDTBOrders:    "SexDTBOrders",
}

// mtbSexR is where relationships are stored.
type mtbSexR struct {
	SexDTBCustomers DTBCustomerSlice
	SexDTBOrders    DTBOrderSlice
}

// NewStruct creates a new relationship struct
func (*mtbSexR) NewStruct() *mtbSexR {
	return &mtbSexR{}
}

// mtbSexL is where Load methods for each relationship are stored.
type mtbSexL struct{}

var (
	mtbSexColumns               = []string{"id", "name", "sort_no", "discriminator_type"}
	mtbSexColumnsWithoutDefault = []string{"id", "name", "sort_no", "discriminator_type"}
	mtbSexColumnsWithDefault    = []string{}
	mtbSexPrimaryKeyColumns     = []string{"id"}
)

type (
	// MTBSexSlice is an alias for a slice of pointers to MTBSex.
	// This should generally be used opposed to []MTBSex.
	MTBSexSlice []*MTBSex
	// MTBSexHook is the signature for custom MTBSex hook methods
	MTBSexHook func(context.Context, boil.ContextExecutor, *MTBSex) error

	mtbSexQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	mtbSexType                 = reflect.TypeOf(&MTBSex{})
	mtbSexMapping              = queries.MakeStructMapping(mtbSexType)
	mtbSexPrimaryKeyMapping, _ = queries.BindMapping(mtbSexType, mtbSexMapping, mtbSexPrimaryKeyColumns)
	mtbSexInsertCacheMut       sync.RWMutex
	mtbSexInsertCache          = make(map[string]insertCache)
	mtbSexUpdateCacheMut       sync.RWMutex
	mtbSexUpdateCache          = make(map[string]updateCache)
	mtbSexUpsertCacheMut       sync.RWMutex
	mtbSexUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var mtbSexBeforeInsertHooks []MTBSexHook
var mtbSexBeforeUpdateHooks []MTBSexHook
var mtbSexBeforeDeleteHooks []MTBSexHook
var mtbSexBeforeUpsertHooks []MTBSexHook

var mtbSexAfterInsertHooks []MTBSexHook
var mtbSexAfterSelectHooks []MTBSexHook
var mtbSexAfterUpdateHooks []MTBSexHook
var mtbSexAfterDeleteHooks []MTBSexHook
var mtbSexAfterUpsertHooks []MTBSexHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MTBSex) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MTBSex) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MTBSex) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MTBSex) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MTBSex) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MTBSex) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MTBSex) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MTBSex) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MTBSex) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbSexAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMTBSexHook registers your hook function for all future operations.
func AddMTBSexHook(hookPoint boil.HookPoint, mtbSexHook MTBSexHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		mtbSexBeforeInsertHooks = append(mtbSexBeforeInsertHooks, mtbSexHook)
	case boil.BeforeUpdateHook:
		mtbSexBeforeUpdateHooks = append(mtbSexBeforeUpdateHooks, mtbSexHook)
	case boil.BeforeDeleteHook:
		mtbSexBeforeDeleteHooks = append(mtbSexBeforeDeleteHooks, mtbSexHook)
	case boil.BeforeUpsertHook:
		mtbSexBeforeUpsertHooks = append(mtbSexBeforeUpsertHooks, mtbSexHook)
	case boil.AfterInsertHook:
		mtbSexAfterInsertHooks = append(mtbSexAfterInsertHooks, mtbSexHook)
	case boil.AfterSelectHook:
		mtbSexAfterSelectHooks = append(mtbSexAfterSelectHooks, mtbSexHook)
	case boil.AfterUpdateHook:
		mtbSexAfterUpdateHooks = append(mtbSexAfterUpdateHooks, mtbSexHook)
	case boil.AfterDeleteHook:
		mtbSexAfterDeleteHooks = append(mtbSexAfterDeleteHooks, mtbSexHook)
	case boil.AfterUpsertHook:
		mtbSexAfterUpsertHooks = append(mtbSexAfterUpsertHooks, mtbSexHook)
	}
}

// One returns a single mtbSex record from the query.
func (q mtbSexQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MTBSex, error) {
	o := &MTBSex{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for mtb_sex")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MTBSex records from the query.
func (q mtbSexQuery) All(ctx context.Context, exec boil.ContextExecutor) (MTBSexSlice, error) {
	var o []*MTBSex

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to MTBSex slice")
	}

	if len(mtbSexAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MTBSex records in the query.
func (q mtbSexQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count mtb_sex rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q mtbSexQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if mtb_sex exists")
	}

	return count > 0, nil
}

// SexDTBCustomers retrieves all the dtb_customer's DTBCustomers with an executor via sex_id column.
func (o *MTBSex) SexDTBCustomers(mods ...qm.QueryMod) dtbCustomerQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`dtb_customer`.`sex_id`=?", o.ID),
	)

	query := DTBCustomers(queryMods...)
	queries.SetFrom(query.Query, "`dtb_customer`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`dtb_customer`.*"})
	}

	return query
}

// SexDTBOrders retrieves all the dtb_order's DTBOrders with an executor via sex_id column.
func (o *MTBSex) SexDTBOrders(mods ...qm.QueryMod) dtbOrderQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`dtb_order`.`sex_id`=?", o.ID),
	)

	query := DTBOrders(queryMods...)
	queries.SetFrom(query.Query, "`dtb_order`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`dtb_order`.*"})
	}

	return query
}

// LoadSexDTBCustomers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (mtbSexL) LoadSexDTBCustomers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMTBSex interface{}, mods queries.Applicator) error {
	var slice []*MTBSex
	var object *MTBSex

	if singular {
		object = maybeMTBSex.(*MTBSex)
	} else {
		slice = *maybeMTBSex.(*[]*MTBSex)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &mtbSexR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &mtbSexR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`dtb_customer`), qm.WhereIn(`sex_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load dtb_customer")
	}

	var resultSlice []*DTBCustomer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice dtb_customer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on dtb_customer")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for dtb_customer")
	}

	if len(dtbCustomerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SexDTBCustomers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dtbCustomerR{}
			}
			foreign.R.Sex = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.SexID) {
				local.R.SexDTBCustomers = append(local.R.SexDTBCustomers, foreign)
				if foreign.R == nil {
					foreign.R = &dtbCustomerR{}
				}
				foreign.R.Sex = local
				break
			}
		}
	}

	return nil
}

// LoadSexDTBOrders allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (mtbSexL) LoadSexDTBOrders(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMTBSex interface{}, mods queries.Applicator) error {
	var slice []*MTBSex
	var object *MTBSex

	if singular {
		object = maybeMTBSex.(*MTBSex)
	} else {
		slice = *maybeMTBSex.(*[]*MTBSex)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &mtbSexR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &mtbSexR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`dtb_order`), qm.WhereIn(`sex_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load dtb_order")
	}

	var resultSlice []*DTBOrder
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice dtb_order")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on dtb_order")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for dtb_order")
	}

	if len(dtbOrderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SexDTBOrders = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dtbOrderR{}
			}
			foreign.R.Sex = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.SexID) {
				local.R.SexDTBOrders = append(local.R.SexDTBOrders, foreign)
				if foreign.R == nil {
					foreign.R = &dtbOrderR{}
				}
				foreign.R.Sex = local
				break
			}
		}
	}

	return nil
}

// AddSexDTBCustomers adds the given related objects to the existing relationships
// of the mtb_sex, optionally inserting them as new records.
// Appends related to o.R.SexDTBCustomers.
// Sets related.R.Sex appropriately.
func (o *MTBSex) AddSexDTBCustomers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DTBCustomer) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SexID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `dtb_customer` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"sex_id"}),
				strmangle.WhereClause("`", "`", 0, dtbCustomerPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SexID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &mtbSexR{
			SexDTBCustomers: related,
		}
	} else {
		o.R.SexDTBCustomers = append(o.R.SexDTBCustomers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dtbCustomerR{
				Sex: o,
			}
		} else {
			rel.R.Sex = o
		}
	}
	return nil
}

// SetSexDTBCustomers removes all previously related items of the
// mtb_sex replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Sex's SexDTBCustomers accordingly.
// Replaces o.R.SexDTBCustomers with related.
// Sets related.R.Sex's SexDTBCustomers accordingly.
func (o *MTBSex) SetSexDTBCustomers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DTBCustomer) error {
	query := "update `dtb_customer` set `sex_id` = null where `sex_id` = ?"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SexDTBCustomers {
			queries.SetScanner(&rel.SexID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Sex = nil
		}

		o.R.SexDTBCustomers = nil
	}
	return o.AddSexDTBCustomers(ctx, exec, insert, related...)
}

// RemoveSexDTBCustomers relationships from objects passed in.
// Removes related items from R.SexDTBCustomers (uses pointer comparison, removal does not keep order)
// Sets related.R.Sex.
func (o *MTBSex) RemoveSexDTBCustomers(ctx context.Context, exec boil.ContextExecutor, related ...*DTBCustomer) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SexID, nil)
		if rel.R != nil {
			rel.R.Sex = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("sex_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SexDTBCustomers {
			if rel != ri {
				continue
			}

			ln := len(o.R.SexDTBCustomers)
			if ln > 1 && i < ln-1 {
				o.R.SexDTBCustomers[i] = o.R.SexDTBCustomers[ln-1]
			}
			o.R.SexDTBCustomers = o.R.SexDTBCustomers[:ln-1]
			break
		}
	}

	return nil
}

// AddSexDTBOrders adds the given related objects to the existing relationships
// of the mtb_sex, optionally inserting them as new records.
// Appends related to o.R.SexDTBOrders.
// Sets related.R.Sex appropriately.
func (o *MTBSex) AddSexDTBOrders(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DTBOrder) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SexID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `dtb_order` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"sex_id"}),
				strmangle.WhereClause("`", "`", 0, dtbOrderPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SexID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &mtbSexR{
			SexDTBOrders: related,
		}
	} else {
		o.R.SexDTBOrders = append(o.R.SexDTBOrders, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dtbOrderR{
				Sex: o,
			}
		} else {
			rel.R.Sex = o
		}
	}
	return nil
}

// SetSexDTBOrders removes all previously related items of the
// mtb_sex replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Sex's SexDTBOrders accordingly.
// Replaces o.R.SexDTBOrders with related.
// Sets related.R.Sex's SexDTBOrders accordingly.
func (o *MTBSex) SetSexDTBOrders(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DTBOrder) error {
	query := "update `dtb_order` set `sex_id` = null where `sex_id` = ?"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SexDTBOrders {
			queries.SetScanner(&rel.SexID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Sex = nil
		}

		o.R.SexDTBOrders = nil
	}
	return o.AddSexDTBOrders(ctx, exec, insert, related...)
}

// RemoveSexDTBOrders relationships from objects passed in.
// Removes related items from R.SexDTBOrders (uses pointer comparison, removal does not keep order)
// Sets related.R.Sex.
func (o *MTBSex) RemoveSexDTBOrders(ctx context.Context, exec boil.ContextExecutor, related ...*DTBOrder) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SexID, nil)
		if rel.R != nil {
			rel.R.Sex = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("sex_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SexDTBOrders {
			if rel != ri {
				continue
			}

			ln := len(o.R.SexDTBOrders)
			if ln > 1 && i < ln-1 {
				o.R.SexDTBOrders[i] = o.R.SexDTBOrders[ln-1]
			}
			o.R.SexDTBOrders = o.R.SexDTBOrders[:ln-1]
			break
		}
	}

	return nil
}

// MTBSexes retrieves all the records using an executor.
func MTBSexes(mods ...qm.QueryMod) mtbSexQuery {
	mods = append(mods, qm.From("`mtb_sex`"))
	return mtbSexQuery{NewQuery(mods...)}
}

// FindMTBSex retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMTBSex(ctx context.Context, exec boil.ContextExecutor, iD uint16, selectCols ...string) (*MTBSex, error) {
	mtbSexObj := &MTBSex{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `mtb_sex` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, mtbSexObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from mtb_sex")
	}

	return mtbSexObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MTBSex) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no mtb_sex provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mtbSexColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	mtbSexInsertCacheMut.RLock()
	cache, cached := mtbSexInsertCache[key]
	mtbSexInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			mtbSexColumns,
			mtbSexColumnsWithDefault,
			mtbSexColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(mtbSexType, mtbSexMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(mtbSexType, mtbSexMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `mtb_sex` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `mtb_sex` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `mtb_sex` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, mtbSexPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into mtb_sex")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for mtb_sex")
	}

CacheNoHooks:
	if !cached {
		mtbSexInsertCacheMut.Lock()
		mtbSexInsertCache[key] = cache
		mtbSexInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MTBSex.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MTBSex) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	mtbSexUpdateCacheMut.RLock()
	cache, cached := mtbSexUpdateCache[key]
	mtbSexUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			mtbSexColumns,
			mtbSexPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update mtb_sex, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `mtb_sex` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, mtbSexPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(mtbSexType, mtbSexMapping, append(wl, mtbSexPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update mtb_sex row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for mtb_sex")
	}

	if !cached {
		mtbSexUpdateCacheMut.Lock()
		mtbSexUpdateCache[key] = cache
		mtbSexUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q mtbSexQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for mtb_sex")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for mtb_sex")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MTBSexSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbSexPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `mtb_sex` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbSexPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in mtbSex slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all mtbSex")
	}
	return rowsAff, nil
}

var mySQLMTBSexUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MTBSex) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no mtb_sex provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mtbSexColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLMTBSexUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	mtbSexUpsertCacheMut.RLock()
	cache, cached := mtbSexUpsertCache[key]
	mtbSexUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			mtbSexColumns,
			mtbSexColumnsWithDefault,
			mtbSexColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			mtbSexColumns,
			mtbSexPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("model: unable to upsert mtb_sex, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "mtb_sex", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `mtb_sex` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(mtbSexType, mtbSexMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(mtbSexType, mtbSexMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for mtb_sex")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(mtbSexType, mtbSexMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "model: unable to retrieve unique values for mtb_sex")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for mtb_sex")
	}

CacheNoHooks:
	if !cached {
		mtbSexUpsertCacheMut.Lock()
		mtbSexUpsertCache[key] = cache
		mtbSexUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MTBSex record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MTBSex) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no MTBSex provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), mtbSexPrimaryKeyMapping)
	sql := "DELETE FROM `mtb_sex` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from mtb_sex")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for mtb_sex")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q mtbSexQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no mtbSexQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from mtb_sex")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for mtb_sex")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MTBSexSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no MTBSex slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(mtbSexBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbSexPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `mtb_sex` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbSexPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from mtbSex slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for mtb_sex")
	}

	if len(mtbSexAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MTBSex) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMTBSex(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MTBSexSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MTBSexSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbSexPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `mtb_sex`.* FROM `mtb_sex` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbSexPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in MTBSexSlice")
	}

	*o = slice

	return nil
}

// MTBSexExists checks if the MTBSex row exists.
func MTBSexExists(ctx context.Context, exec boil.ContextExecutor, iD uint16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `mtb_sex` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if mtb_sex exists")
	}

	return exists, nil
}
