// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMTBRoundingTypes(t *testing.T) {
	t.Parallel()

	query := MTBRoundingTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMTBRoundingTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBRoundingTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MTBRoundingTypes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBRoundingTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTBRoundingTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBRoundingTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MTBRoundingTypeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MTBRoundingType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MTBRoundingTypeExists to return true, but got false.")
	}
}

func testMTBRoundingTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mtbRoundingTypeFound, err := FindMTBRoundingType(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mtbRoundingTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMTBRoundingTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MTBRoundingTypes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMTBRoundingTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MTBRoundingTypes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMTBRoundingTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mtbRoundingTypeOne := &MTBRoundingType{}
	mtbRoundingTypeTwo := &MTBRoundingType{}
	if err = randomize.Struct(seed, mtbRoundingTypeOne, mtbRoundingTypeDBTypes, false, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}
	if err = randomize.Struct(seed, mtbRoundingTypeTwo, mtbRoundingTypeDBTypes, false, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mtbRoundingTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mtbRoundingTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTBRoundingTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMTBRoundingTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mtbRoundingTypeOne := &MTBRoundingType{}
	mtbRoundingTypeTwo := &MTBRoundingType{}
	if err = randomize.Struct(seed, mtbRoundingTypeOne, mtbRoundingTypeDBTypes, false, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}
	if err = randomize.Struct(seed, mtbRoundingTypeTwo, mtbRoundingTypeDBTypes, false, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mtbRoundingTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mtbRoundingTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func mtbRoundingTypeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func mtbRoundingTypeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBRoundingType) error {
	*o = MTBRoundingType{}
	return nil
}

func testMTBRoundingTypesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MTBRoundingType{}
	o := &MTBRoundingType{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType object: %s", err)
	}

	AddMTBRoundingTypeHook(boil.BeforeInsertHook, mtbRoundingTypeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeBeforeInsertHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.AfterInsertHook, mtbRoundingTypeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeAfterInsertHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.AfterSelectHook, mtbRoundingTypeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeAfterSelectHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.BeforeUpdateHook, mtbRoundingTypeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeBeforeUpdateHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.AfterUpdateHook, mtbRoundingTypeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeAfterUpdateHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.BeforeDeleteHook, mtbRoundingTypeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeBeforeDeleteHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.AfterDeleteHook, mtbRoundingTypeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeAfterDeleteHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.BeforeUpsertHook, mtbRoundingTypeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeBeforeUpsertHooks = []MTBRoundingTypeHook{}

	AddMTBRoundingTypeHook(boil.AfterUpsertHook, mtbRoundingTypeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	mtbRoundingTypeAfterUpsertHooks = []MTBRoundingTypeHook{}
}

func testMTBRoundingTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTBRoundingTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mtbRoundingTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTBRoundingTypeToManyRoundingTypeDTBOrderItems(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, dtbOrderItemDBTypes, false, dtbOrderItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, dtbOrderItemDBTypes, false, dtbOrderItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.RoundingTypeID, a.ID)
	queries.Assign(&c.RoundingTypeID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RoundingTypeDTBOrderItems().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.RoundingTypeID, b.RoundingTypeID) {
			bFound = true
		}
		if queries.Equal(v.RoundingTypeID, c.RoundingTypeID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MTBRoundingTypeSlice{&a}
	if err = a.L.LoadRoundingTypeDTBOrderItems(ctx, tx, false, (*[]*MTBRoundingType)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoundingTypeDTBOrderItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RoundingTypeDTBOrderItems = nil
	if err = a.L.LoadRoundingTypeDTBOrderItems(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoundingTypeDTBOrderItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMTBRoundingTypeToManyRoundingTypeDTBTaxRules(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c DTBTaxRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, dtbTaxRuleDBTypes, false, dtbTaxRuleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, dtbTaxRuleDBTypes, false, dtbTaxRuleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.RoundingTypeID, a.ID)
	queries.Assign(&c.RoundingTypeID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RoundingTypeDTBTaxRules().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.RoundingTypeID, b.RoundingTypeID) {
			bFound = true
		}
		if queries.Equal(v.RoundingTypeID, c.RoundingTypeID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MTBRoundingTypeSlice{&a}
	if err = a.L.LoadRoundingTypeDTBTaxRules(ctx, tx, false, (*[]*MTBRoundingType)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoundingTypeDTBTaxRules); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RoundingTypeDTBTaxRules = nil
	if err = a.L.LoadRoundingTypeDTBTaxRules(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoundingTypeDTBTaxRules); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMTBRoundingTypeToManyAddOpRoundingTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*DTBOrderItem{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRoundingTypeDTBOrderItems(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.RoundingTypeID) {
			t.Error("foreign key was wrong value", a.ID, first.RoundingTypeID)
		}
		if !queries.Equal(a.ID, second.RoundingTypeID) {
			t.Error("foreign key was wrong value", a.ID, second.RoundingTypeID)
		}

		if first.R.RoundingType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.RoundingType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RoundingTypeDTBOrderItems[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RoundingTypeDTBOrderItems[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RoundingTypeDTBOrderItems().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMTBRoundingTypeToManySetOpRoundingTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRoundingTypeDTBOrderItems(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RoundingTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRoundingTypeDTBOrderItems(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RoundingTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoundingTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoundingTypeID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.RoundingTypeID) {
		t.Error("foreign key was wrong value", a.ID, d.RoundingTypeID)
	}
	if !queries.Equal(a.ID, e.RoundingTypeID) {
		t.Error("foreign key was wrong value", a.ID, e.RoundingTypeID)
	}

	if b.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RoundingType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RoundingType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RoundingTypeDTBOrderItems[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RoundingTypeDTBOrderItems[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testMTBRoundingTypeToManyRemoveOpRoundingTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRoundingTypeDTBOrderItems(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RoundingTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRoundingTypeDTBOrderItems(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RoundingTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoundingTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoundingTypeID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RoundingType != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.RoundingType != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RoundingTypeDTBOrderItems) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RoundingTypeDTBOrderItems[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RoundingTypeDTBOrderItems[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testMTBRoundingTypeToManyAddOpRoundingTypeDTBTaxRules(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBTaxRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBTaxRule{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbTaxRuleDBTypes, false, strmangle.SetComplement(dtbTaxRulePrimaryKeyColumns, dtbTaxRuleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*DTBTaxRule{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRoundingTypeDTBTaxRules(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.RoundingTypeID) {
			t.Error("foreign key was wrong value", a.ID, first.RoundingTypeID)
		}
		if !queries.Equal(a.ID, second.RoundingTypeID) {
			t.Error("foreign key was wrong value", a.ID, second.RoundingTypeID)
		}

		if first.R.RoundingType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.RoundingType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RoundingTypeDTBTaxRules[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RoundingTypeDTBTaxRules[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RoundingTypeDTBTaxRules().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMTBRoundingTypeToManySetOpRoundingTypeDTBTaxRules(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBTaxRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBTaxRule{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbTaxRuleDBTypes, false, strmangle.SetComplement(dtbTaxRulePrimaryKeyColumns, dtbTaxRuleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRoundingTypeDTBTaxRules(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RoundingTypeDTBTaxRules().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRoundingTypeDTBTaxRules(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RoundingTypeDTBTaxRules().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoundingTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoundingTypeID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.RoundingTypeID) {
		t.Error("foreign key was wrong value", a.ID, d.RoundingTypeID)
	}
	if !queries.Equal(a.ID, e.RoundingTypeID) {
		t.Error("foreign key was wrong value", a.ID, e.RoundingTypeID)
	}

	if b.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RoundingType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RoundingType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RoundingTypeDTBTaxRules[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RoundingTypeDTBTaxRules[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testMTBRoundingTypeToManyRemoveOpRoundingTypeDTBTaxRules(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBRoundingType
	var b, c, d, e DTBTaxRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbRoundingTypeDBTypes, false, strmangle.SetComplement(mtbRoundingTypePrimaryKeyColumns, mtbRoundingTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBTaxRule{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbTaxRuleDBTypes, false, strmangle.SetComplement(dtbTaxRulePrimaryKeyColumns, dtbTaxRuleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRoundingTypeDTBTaxRules(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RoundingTypeDTBTaxRules().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRoundingTypeDTBTaxRules(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RoundingTypeDTBTaxRules().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoundingTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoundingTypeID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RoundingType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RoundingType != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.RoundingType != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RoundingTypeDTBTaxRules) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RoundingTypeDTBTaxRules[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RoundingTypeDTBTaxRules[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testMTBRoundingTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTBRoundingTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTBRoundingTypeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTBRoundingTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTBRoundingTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mtbRoundingTypeDBTypes = map[string]string{`ID`: `smallint`, `Name`: `varchar`, `SortNo`: `smallint`, `DiscriminatorType`: `varchar`}
	_                      = bytes.MinRead
)

func testMTBRoundingTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mtbRoundingTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mtbRoundingTypeColumns) == len(mtbRoundingTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMTBRoundingTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mtbRoundingTypeColumns) == len(mtbRoundingTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTBRoundingType{}
	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mtbRoundingTypeDBTypes, true, mtbRoundingTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mtbRoundingTypeColumns, mtbRoundingTypePrimaryKeyColumns) {
		fields = mtbRoundingTypeColumns
	} else {
		fields = strmangle.SetComplement(
			mtbRoundingTypeColumns,
			mtbRoundingTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MTBRoundingTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMTBRoundingTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(mtbRoundingTypeColumns) == len(mtbRoundingTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLMTBRoundingTypeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MTBRoundingType{}
	if err = randomize.Struct(seed, &o, mtbRoundingTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTBRoundingType: %s", err)
	}

	count, err := MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mtbRoundingTypeDBTypes, false, mtbRoundingTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBRoundingType struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTBRoundingType: %s", err)
	}

	count, err = MTBRoundingTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
