// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// MTBCustomerOrderStatus is an object representing the database table.
type MTBCustomerOrderStatus struct {
	ID                uint16 `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name              string `boil:"name" json:"name" toml:"name" yaml:"name"`
	SortNo            uint16 `boil:"sort_no" json:"sort_no" toml:"sort_no" yaml:"sort_no"`
	DiscriminatorType string `boil:"discriminator_type" json:"discriminator_type" toml:"discriminator_type" yaml:"discriminator_type"`

	R *mtbCustomerOrderStatusR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L mtbCustomerOrderStatusL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MTBCustomerOrderStatusColumns = struct {
	ID                string
	Name              string
	SortNo            string
	DiscriminatorType string
}{
	ID:                "id",
	Name:              "name",
	SortNo:            "sort_no",
	DiscriminatorType: "discriminator_type",
}

// Generated where

var MTBCustomerOrderStatusWhere = struct {
	ID                whereHelperuint16
	Name              whereHelperstring
	SortNo            whereHelperuint16
	DiscriminatorType whereHelperstring
}{
	ID:                whereHelperuint16{field: `id`},
	Name:              whereHelperstring{field: `name`},
	SortNo:            whereHelperuint16{field: `sort_no`},
	DiscriminatorType: whereHelperstring{field: `discriminator_type`},
}

// MTBCustomerOrderStatusRels is where relationship names are stored.
var MTBCustomerOrderStatusRels = struct {
}{}

// mtbCustomerOrderStatusR is where relationships are stored.
type mtbCustomerOrderStatusR struct {
}

// NewStruct creates a new relationship struct
func (*mtbCustomerOrderStatusR) NewStruct() *mtbCustomerOrderStatusR {
	return &mtbCustomerOrderStatusR{}
}

// mtbCustomerOrderStatusL is where Load methods for each relationship are stored.
type mtbCustomerOrderStatusL struct{}

var (
	mtbCustomerOrderStatusColumns               = []string{"id", "name", "sort_no", "discriminator_type"}
	mtbCustomerOrderStatusColumnsWithoutDefault = []string{"id", "name", "sort_no", "discriminator_type"}
	mtbCustomerOrderStatusColumnsWithDefault    = []string{}
	mtbCustomerOrderStatusPrimaryKeyColumns     = []string{"id"}
)

type (
	// MTBCustomerOrderStatusSlice is an alias for a slice of pointers to MTBCustomerOrderStatus.
	// This should generally be used opposed to []MTBCustomerOrderStatus.
	MTBCustomerOrderStatusSlice []*MTBCustomerOrderStatus
	// MTBCustomerOrderStatusHook is the signature for custom MTBCustomerOrderStatus hook methods
	MTBCustomerOrderStatusHook func(context.Context, boil.ContextExecutor, *MTBCustomerOrderStatus) error

	mtbCustomerOrderStatusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	mtbCustomerOrderStatusType                 = reflect.TypeOf(&MTBCustomerOrderStatus{})
	mtbCustomerOrderStatusMapping              = queries.MakeStructMapping(mtbCustomerOrderStatusType)
	mtbCustomerOrderStatusPrimaryKeyMapping, _ = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, mtbCustomerOrderStatusPrimaryKeyColumns)
	mtbCustomerOrderStatusInsertCacheMut       sync.RWMutex
	mtbCustomerOrderStatusInsertCache          = make(map[string]insertCache)
	mtbCustomerOrderStatusUpdateCacheMut       sync.RWMutex
	mtbCustomerOrderStatusUpdateCache          = make(map[string]updateCache)
	mtbCustomerOrderStatusUpsertCacheMut       sync.RWMutex
	mtbCustomerOrderStatusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var mtbCustomerOrderStatusBeforeInsertHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusBeforeUpdateHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusBeforeDeleteHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusBeforeUpsertHooks []MTBCustomerOrderStatusHook

var mtbCustomerOrderStatusAfterInsertHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusAfterSelectHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusAfterUpdateHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusAfterDeleteHooks []MTBCustomerOrderStatusHook
var mtbCustomerOrderStatusAfterUpsertHooks []MTBCustomerOrderStatusHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MTBCustomerOrderStatus) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MTBCustomerOrderStatus) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MTBCustomerOrderStatus) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MTBCustomerOrderStatus) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MTBCustomerOrderStatus) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MTBCustomerOrderStatus) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MTBCustomerOrderStatus) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MTBCustomerOrderStatus) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MTBCustomerOrderStatus) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mtbCustomerOrderStatusAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMTBCustomerOrderStatusHook registers your hook function for all future operations.
func AddMTBCustomerOrderStatusHook(hookPoint boil.HookPoint, mtbCustomerOrderStatusHook MTBCustomerOrderStatusHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		mtbCustomerOrderStatusBeforeInsertHooks = append(mtbCustomerOrderStatusBeforeInsertHooks, mtbCustomerOrderStatusHook)
	case boil.BeforeUpdateHook:
		mtbCustomerOrderStatusBeforeUpdateHooks = append(mtbCustomerOrderStatusBeforeUpdateHooks, mtbCustomerOrderStatusHook)
	case boil.BeforeDeleteHook:
		mtbCustomerOrderStatusBeforeDeleteHooks = append(mtbCustomerOrderStatusBeforeDeleteHooks, mtbCustomerOrderStatusHook)
	case boil.BeforeUpsertHook:
		mtbCustomerOrderStatusBeforeUpsertHooks = append(mtbCustomerOrderStatusBeforeUpsertHooks, mtbCustomerOrderStatusHook)
	case boil.AfterInsertHook:
		mtbCustomerOrderStatusAfterInsertHooks = append(mtbCustomerOrderStatusAfterInsertHooks, mtbCustomerOrderStatusHook)
	case boil.AfterSelectHook:
		mtbCustomerOrderStatusAfterSelectHooks = append(mtbCustomerOrderStatusAfterSelectHooks, mtbCustomerOrderStatusHook)
	case boil.AfterUpdateHook:
		mtbCustomerOrderStatusAfterUpdateHooks = append(mtbCustomerOrderStatusAfterUpdateHooks, mtbCustomerOrderStatusHook)
	case boil.AfterDeleteHook:
		mtbCustomerOrderStatusAfterDeleteHooks = append(mtbCustomerOrderStatusAfterDeleteHooks, mtbCustomerOrderStatusHook)
	case boil.AfterUpsertHook:
		mtbCustomerOrderStatusAfterUpsertHooks = append(mtbCustomerOrderStatusAfterUpsertHooks, mtbCustomerOrderStatusHook)
	}
}

// One returns a single mtbCustomerOrderStatus record from the query.
func (q mtbCustomerOrderStatusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MTBCustomerOrderStatus, error) {
	o := &MTBCustomerOrderStatus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for mtb_customer_order_status")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MTBCustomerOrderStatus records from the query.
func (q mtbCustomerOrderStatusQuery) All(ctx context.Context, exec boil.ContextExecutor) (MTBCustomerOrderStatusSlice, error) {
	var o []*MTBCustomerOrderStatus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to MTBCustomerOrderStatus slice")
	}

	if len(mtbCustomerOrderStatusAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MTBCustomerOrderStatus records in the query.
func (q mtbCustomerOrderStatusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count mtb_customer_order_status rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q mtbCustomerOrderStatusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if mtb_customer_order_status exists")
	}

	return count > 0, nil
}

// MTBCustomerOrderStatuses retrieves all the records using an executor.
func MTBCustomerOrderStatuses(mods ...qm.QueryMod) mtbCustomerOrderStatusQuery {
	mods = append(mods, qm.From("`mtb_customer_order_status`"))
	return mtbCustomerOrderStatusQuery{NewQuery(mods...)}
}

// FindMTBCustomerOrderStatus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMTBCustomerOrderStatus(ctx context.Context, exec boil.ContextExecutor, iD uint16, selectCols ...string) (*MTBCustomerOrderStatus, error) {
	mtbCustomerOrderStatusObj := &MTBCustomerOrderStatus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `mtb_customer_order_status` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, mtbCustomerOrderStatusObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from mtb_customer_order_status")
	}

	return mtbCustomerOrderStatusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MTBCustomerOrderStatus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no mtb_customer_order_status provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mtbCustomerOrderStatusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	mtbCustomerOrderStatusInsertCacheMut.RLock()
	cache, cached := mtbCustomerOrderStatusInsertCache[key]
	mtbCustomerOrderStatusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			mtbCustomerOrderStatusColumns,
			mtbCustomerOrderStatusColumnsWithDefault,
			mtbCustomerOrderStatusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `mtb_customer_order_status` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `mtb_customer_order_status` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `mtb_customer_order_status` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, mtbCustomerOrderStatusPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into mtb_customer_order_status")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for mtb_customer_order_status")
	}

CacheNoHooks:
	if !cached {
		mtbCustomerOrderStatusInsertCacheMut.Lock()
		mtbCustomerOrderStatusInsertCache[key] = cache
		mtbCustomerOrderStatusInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MTBCustomerOrderStatus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MTBCustomerOrderStatus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	mtbCustomerOrderStatusUpdateCacheMut.RLock()
	cache, cached := mtbCustomerOrderStatusUpdateCache[key]
	mtbCustomerOrderStatusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			mtbCustomerOrderStatusColumns,
			mtbCustomerOrderStatusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update mtb_customer_order_status, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `mtb_customer_order_status` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, mtbCustomerOrderStatusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, append(wl, mtbCustomerOrderStatusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update mtb_customer_order_status row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for mtb_customer_order_status")
	}

	if !cached {
		mtbCustomerOrderStatusUpdateCacheMut.Lock()
		mtbCustomerOrderStatusUpdateCache[key] = cache
		mtbCustomerOrderStatusUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q mtbCustomerOrderStatusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for mtb_customer_order_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for mtb_customer_order_status")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MTBCustomerOrderStatusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbCustomerOrderStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `mtb_customer_order_status` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbCustomerOrderStatusPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in mtbCustomerOrderStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all mtbCustomerOrderStatus")
	}
	return rowsAff, nil
}

var mySQLMTBCustomerOrderStatusUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MTBCustomerOrderStatus) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no mtb_customer_order_status provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mtbCustomerOrderStatusColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLMTBCustomerOrderStatusUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	mtbCustomerOrderStatusUpsertCacheMut.RLock()
	cache, cached := mtbCustomerOrderStatusUpsertCache[key]
	mtbCustomerOrderStatusUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			mtbCustomerOrderStatusColumns,
			mtbCustomerOrderStatusColumnsWithDefault,
			mtbCustomerOrderStatusColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			mtbCustomerOrderStatusColumns,
			mtbCustomerOrderStatusPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("model: unable to upsert mtb_customer_order_status, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "mtb_customer_order_status", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `mtb_customer_order_status` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for mtb_customer_order_status")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(mtbCustomerOrderStatusType, mtbCustomerOrderStatusMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "model: unable to retrieve unique values for mtb_customer_order_status")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for mtb_customer_order_status")
	}

CacheNoHooks:
	if !cached {
		mtbCustomerOrderStatusUpsertCacheMut.Lock()
		mtbCustomerOrderStatusUpsertCache[key] = cache
		mtbCustomerOrderStatusUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MTBCustomerOrderStatus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MTBCustomerOrderStatus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no MTBCustomerOrderStatus provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), mtbCustomerOrderStatusPrimaryKeyMapping)
	sql := "DELETE FROM `mtb_customer_order_status` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from mtb_customer_order_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for mtb_customer_order_status")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q mtbCustomerOrderStatusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no mtbCustomerOrderStatusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from mtb_customer_order_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for mtb_customer_order_status")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MTBCustomerOrderStatusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no MTBCustomerOrderStatus slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(mtbCustomerOrderStatusBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbCustomerOrderStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `mtb_customer_order_status` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbCustomerOrderStatusPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from mtbCustomerOrderStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for mtb_customer_order_status")
	}

	if len(mtbCustomerOrderStatusAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MTBCustomerOrderStatus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMTBCustomerOrderStatus(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MTBCustomerOrderStatusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MTBCustomerOrderStatusSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mtbCustomerOrderStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `mtb_customer_order_status`.* FROM `mtb_customer_order_status` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mtbCustomerOrderStatusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in MTBCustomerOrderStatusSlice")
	}

	*o = slice

	return nil
}

// MTBCustomerOrderStatusExists checks if the MTBCustomerOrderStatus row exists.
func MTBCustomerOrderStatusExists(ctx context.Context, exec boil.ContextExecutor, iD uint16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `mtb_customer_order_status` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if mtb_customer_order_status exists")
	}

	return exists, nil
}
