// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMTBOrderItemTypes(t *testing.T) {
	t.Parallel()

	query := MTBOrderItemTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMTBOrderItemTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBOrderItemTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MTBOrderItemTypes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBOrderItemTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTBOrderItemTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTBOrderItemTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MTBOrderItemTypeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MTBOrderItemType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MTBOrderItemTypeExists to return true, but got false.")
	}
}

func testMTBOrderItemTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mtbOrderItemTypeFound, err := FindMTBOrderItemType(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mtbOrderItemTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMTBOrderItemTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MTBOrderItemTypes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMTBOrderItemTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MTBOrderItemTypes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMTBOrderItemTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mtbOrderItemTypeOne := &MTBOrderItemType{}
	mtbOrderItemTypeTwo := &MTBOrderItemType{}
	if err = randomize.Struct(seed, mtbOrderItemTypeOne, mtbOrderItemTypeDBTypes, false, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}
	if err = randomize.Struct(seed, mtbOrderItemTypeTwo, mtbOrderItemTypeDBTypes, false, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mtbOrderItemTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mtbOrderItemTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTBOrderItemTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMTBOrderItemTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mtbOrderItemTypeOne := &MTBOrderItemType{}
	mtbOrderItemTypeTwo := &MTBOrderItemType{}
	if err = randomize.Struct(seed, mtbOrderItemTypeOne, mtbOrderItemTypeDBTypes, false, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}
	if err = randomize.Struct(seed, mtbOrderItemTypeTwo, mtbOrderItemTypeDBTypes, false, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mtbOrderItemTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mtbOrderItemTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func mtbOrderItemTypeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func mtbOrderItemTypeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MTBOrderItemType) error {
	*o = MTBOrderItemType{}
	return nil
}

func testMTBOrderItemTypesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MTBOrderItemType{}
	o := &MTBOrderItemType{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType object: %s", err)
	}

	AddMTBOrderItemTypeHook(boil.BeforeInsertHook, mtbOrderItemTypeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeBeforeInsertHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.AfterInsertHook, mtbOrderItemTypeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeAfterInsertHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.AfterSelectHook, mtbOrderItemTypeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeAfterSelectHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.BeforeUpdateHook, mtbOrderItemTypeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeBeforeUpdateHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.AfterUpdateHook, mtbOrderItemTypeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeAfterUpdateHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.BeforeDeleteHook, mtbOrderItemTypeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeBeforeDeleteHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.AfterDeleteHook, mtbOrderItemTypeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeAfterDeleteHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.BeforeUpsertHook, mtbOrderItemTypeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeBeforeUpsertHooks = []MTBOrderItemTypeHook{}

	AddMTBOrderItemTypeHook(boil.AfterUpsertHook, mtbOrderItemTypeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	mtbOrderItemTypeAfterUpsertHooks = []MTBOrderItemTypeHook{}
}

func testMTBOrderItemTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTBOrderItemTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mtbOrderItemTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTBOrderItemTypeToManyOrderItemTypeDTBOrderItems(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBOrderItemType
	var b, c DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, dtbOrderItemDBTypes, false, dtbOrderItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, dtbOrderItemDBTypes, false, dtbOrderItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.OrderItemTypeID, a.ID)
	queries.Assign(&c.OrderItemTypeID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.OrderItemTypeDTBOrderItems().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.OrderItemTypeID, b.OrderItemTypeID) {
			bFound = true
		}
		if queries.Equal(v.OrderItemTypeID, c.OrderItemTypeID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MTBOrderItemTypeSlice{&a}
	if err = a.L.LoadOrderItemTypeDTBOrderItems(ctx, tx, false, (*[]*MTBOrderItemType)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.OrderItemTypeDTBOrderItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.OrderItemTypeDTBOrderItems = nil
	if err = a.L.LoadOrderItemTypeDTBOrderItems(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.OrderItemTypeDTBOrderItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMTBOrderItemTypeToManyAddOpOrderItemTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBOrderItemType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbOrderItemTypeDBTypes, false, strmangle.SetComplement(mtbOrderItemTypePrimaryKeyColumns, mtbOrderItemTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*DTBOrderItem{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddOrderItemTypeDTBOrderItems(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.OrderItemTypeID) {
			t.Error("foreign key was wrong value", a.ID, first.OrderItemTypeID)
		}
		if !queries.Equal(a.ID, second.OrderItemTypeID) {
			t.Error("foreign key was wrong value", a.ID, second.OrderItemTypeID)
		}

		if first.R.OrderItemType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.OrderItemType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.OrderItemTypeDTBOrderItems[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.OrderItemTypeDTBOrderItems[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.OrderItemTypeDTBOrderItems().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMTBOrderItemTypeToManySetOpOrderItemTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBOrderItemType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbOrderItemTypeDBTypes, false, strmangle.SetComplement(mtbOrderItemTypePrimaryKeyColumns, mtbOrderItemTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetOrderItemTypeDTBOrderItems(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.OrderItemTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetOrderItemTypeDTBOrderItems(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.OrderItemTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.OrderItemTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.OrderItemTypeID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.OrderItemTypeID) {
		t.Error("foreign key was wrong value", a.ID, d.OrderItemTypeID)
	}
	if !queries.Equal(a.ID, e.OrderItemTypeID) {
		t.Error("foreign key was wrong value", a.ID, e.OrderItemTypeID)
	}

	if b.R.OrderItemType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.OrderItemType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.OrderItemType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.OrderItemType != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.OrderItemTypeDTBOrderItems[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.OrderItemTypeDTBOrderItems[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testMTBOrderItemTypeToManyRemoveOpOrderItemTypeDTBOrderItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MTBOrderItemType
	var b, c, d, e DTBOrderItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mtbOrderItemTypeDBTypes, false, strmangle.SetComplement(mtbOrderItemTypePrimaryKeyColumns, mtbOrderItemTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DTBOrderItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, dtbOrderItemDBTypes, false, strmangle.SetComplement(dtbOrderItemPrimaryKeyColumns, dtbOrderItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddOrderItemTypeDTBOrderItems(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.OrderItemTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveOrderItemTypeDTBOrderItems(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.OrderItemTypeDTBOrderItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.OrderItemTypeID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.OrderItemTypeID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.OrderItemType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.OrderItemType != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.OrderItemType != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.OrderItemType != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.OrderItemTypeDTBOrderItems) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.OrderItemTypeDTBOrderItems[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.OrderItemTypeDTBOrderItems[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testMTBOrderItemTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTBOrderItemTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTBOrderItemTypeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTBOrderItemTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTBOrderItemTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mtbOrderItemTypeDBTypes = map[string]string{`ID`: `smallint`, `Name`: `varchar`, `SortNo`: `smallint`, `DiscriminatorType`: `varchar`}
	_                       = bytes.MinRead
)

func testMTBOrderItemTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mtbOrderItemTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mtbOrderItemTypeColumns) == len(mtbOrderItemTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMTBOrderItemTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mtbOrderItemTypeColumns) == len(mtbOrderItemTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTBOrderItemType{}
	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mtbOrderItemTypeDBTypes, true, mtbOrderItemTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mtbOrderItemTypeColumns, mtbOrderItemTypePrimaryKeyColumns) {
		fields = mtbOrderItemTypeColumns
	} else {
		fields = strmangle.SetComplement(
			mtbOrderItemTypeColumns,
			mtbOrderItemTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MTBOrderItemTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMTBOrderItemTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(mtbOrderItemTypeColumns) == len(mtbOrderItemTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLMTBOrderItemTypeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MTBOrderItemType{}
	if err = randomize.Struct(seed, &o, mtbOrderItemTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTBOrderItemType: %s", err)
	}

	count, err := MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mtbOrderItemTypeDBTypes, false, mtbOrderItemTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTBOrderItemType struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTBOrderItemType: %s", err)
	}

	count, err = MTBOrderItemTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
